# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Muscovite-Commercial
import os
import textwrap

from conan import ConanFile
from conan.tools.cmake import CMakeDeps, CMakeToolchain, cmake_layout
from conan.tools.files import save


class MuscoviteHarborConan(ConanFile):
    name = "muscovite_harbor"
    version = "0.2.0"
    settings = "os", "compiler", "build_type", "arch"

    default_options = {
        "muscovite/*:shared": True,
    }

    def requirements(self):
        self.requires("muscovite/2.25.18")

    def build_requirements(self):
        self.tool_requires("muscomp/2.25.18")

    def layout(self):
        cmake_layout(self)

    def generate(self):
        deps = CMakeDeps(self)
        deps.generate()
        tc = CMakeToolchain(self)
        tc.generate()

        # Workaround: Several Conan recipes (spdlog, fmt, boost, etc.) use
        # cpp_info.components but leave component-level includedirs empty.
        # When system -devel packages provide headers at /usr/include, the
        # compiler picks up the wrong version — causing ABI mismatches or
        # link failures.
        #
        # Note: protobuf, gRPC, and abseil are system packages since
        # muscovite 2.25.14 — they are NOT patched here.
        #
        # Fix: iterate every imported target and, if its namespace matches a
        # Conan package, unconditionally append that package's include dir.
        lines = [
            '# Generated by conanfile.py — Conan include-dir fixup',
            '',
            'function(_conan_fix_inc _target _dir)',
            '  if(TARGET ${_target})',
            '    set_property(TARGET ${_target} APPEND PROPERTY',
            '      INTERFACE_INCLUDE_DIRECTORIES "${_dir}")',
            '  endif()',
            'endfunction()',
            '',
        ]

        # Map CMake target namespace prefixes → Conan dependency ref names.
        # Keys are regex-safe prefixes used in if(_t MATCHES "^<prefix>::").
        # protobuf, gRPC, abseil, and re2 are system packages since
        # muscovite 2.25.14 — do NOT include them here.
        ns_to_dep = {
            "spdlog":         "spdlog",
            "fmt":            "fmt",
            "Boost":          "boost",
            "boost":          "boost",
            "openssl":        "openssl",
            "OpenSSL":        "openssl",
            "opentelemetry":  "opentelemetry-cpp",
            "CURL":           "libcurl",
            "libpqxx":        "libpqxx",
            "ZLIB":           "zlib",
        }

        # Resolve actual include dirs from the dependency graph.
        dep_inc = {}  # dep ref name → include path
        for dep_ref, dep_info in self.dependencies.items():
            if dep_info.context != "host":
                continue
            pkg = dep_info.package_folder
            if pkg is None:
                continue
            inc = os.path.join(pkg, "include")
            if os.path.isdir(inc):
                dep_inc[str(dep_ref).split("/")[0]] = inc.replace("\\", "/")

        # Emit cmake variables for each resolved include dir.
        used = {}
        for ns, dep_name in ns_to_dep.items():
            if dep_name in dep_inc and dep_name not in used:
                safe = dep_name.upper().replace("-", "_")
                lines.append(f'set(_CONAN_{safe}_INC "{dep_inc[dep_name]}")')
                used[dep_name] = safe

        # Single loop over all imported targets.
        lines.append('')
        lines.append('get_property(_all_targets DIRECTORY PROPERTY IMPORTED_TARGETS)')
        lines.append('foreach(_t ${_all_targets})')
        for ns, dep_name in ns_to_dep.items():
            if dep_name in used:
                var = f'_CONAN_{used[dep_name]}_INC'
                lines.append(f'  if(_t MATCHES "^{ns}::")')
                lines.append(f'    _conan_fix_inc(${{_t}} "${{{var}}}")')
                lines.append('  endif()')
        lines.append('endforeach()')

        gen_dir = os.path.join(self.build_folder, "generators")
        save(self, os.path.join(gen_dir, "conan_include_fixup.cmake"),
             "\n".join(lines))
