# Generated by muscomp --create
from conan import ConanFile
from conan.tools.cmake import CMake, cmake_layout


class MuscoviteHarborConan(ConanFile):
    name = "muscovite-harbor"
    version = "0.1.0"
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps", "CMakeToolchain"

    def requirements(self):
        self.requires("muscovite/[>=2.24.0]")

    def build_requirements(self):
        # muscomp Conan packaging broken (opensourcedruidhills/muscovite#1453)
        # Use muscomp binary from PATH until fixed
        pass

    def layout(self):
        cmake_layout(self)

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
