# Generated by muscomp --create
from conan import ConanFile
from conan.tools.cmake import CMake, cmake_layout


class MuscoviteHarborConan(ConanFile):
    name = "muscovite-harbor"
    version = "0.1.0"
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeDeps", "CMakeToolchain"

    def requirements(self):
        self.requires("muscovite/[>=2.24.0]")

    def build_requirements(self):
        self.tool_requires("muscomp/[>=2.25.0]")

    def layout(self):
        cmake_layout(self)

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
